spring.application.name=movie-info-service
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


eureka.instance.prefer-ip-address=true
#
## Logging level for troubleshooting
#logging.level.com.netflix.eureka=DEBUG
#logging.level.com.netflix.discovery=DEBUG


#movie-bd username= pks9 pwd = 1234
api_key=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzMDI4NDQ5YjY5MjAzOGI3MDE3MjhjMjNhZjNkYmQ2NiIsIm5iZiI6MTc2NjUxNDc0OS44NDYwMDAyLCJzdWIiOiI2OTRhZTAzZGMyYjg4MDYwYTI3YWNhMzciLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.mixOR81zUNBsEr4BXE2WXOT1DAzgruv83tD_oy3SYuk

#API read access token
#eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzMDI4NDQ5YjY5MjAzOGI3MDE3MjhjMjNhZjNkYmQ2NiIsIm5iZiI6MTc2NjUxNDc0OS44NDYwMDAyLCJzdWIiOiI2OTRhZTAzZGMyYjg4MDYwYTI3YWNhMzciLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.mixOR81zUNBsEr4BXE2WXOT1DAzgruv83tD_oy3SYuk