spring.application.name=movie-catalog-service
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreaker-events
management.endpoint.circuitbreakers.enabled=true
management.endpoint.circuitbreaker-events.enabled=true
resilience4j.circuitbreaker.instances.movieInfo.slidingWindowSize=5
resilience4j.circuitbreaker.instances.movieInfo.failureRateThreshold=50
resilience4j.circuitbreaker.instances.movieInfo.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.movieInfo.permittedNumberOfCallsInHalfOpenState=2
resilience4j.retry.instances.movieInfo.maxAttempts=3
resilience4j.retry.instances.movieInfo.waitDuration=1s
logging.level.io.github.resilience4j.retry=DEBUG

